### ISSUE TITLE
Lesson 210 - GOMAXPROCS and K8s CFS scheduler

### ISSUE THREAD

**Issue by agravelot** [antonputra/tutorials#289]
If your k8s node has more cpus than your deployment limit, the golang scheduler will not be aware of the kubernetes CFS scheduler, leading to many/all coroutines in a sleep state, false result.
Setting `GOMAXPROCS=2` as in k8s deployment can lead to better performance.

https://github.com/uber-go/automaxprocs is specially designed for this purpose.

Related discussion: https://github.com/antonputra/tutorials/pull/288

**Comment by agravelot** [comment]
I hadn't noticed this PR: https://github.com/antonputra/tutorials/pull/278
The problem is better explained, but may still be relevant to the current branch.

**Comment by antonputra** [comment]
Thank you, @agravelot! I did some more research and even ran tests. You're right—GOMAXPROCS makes a significant difference! I'll be using it in all my future benchmarks.

```yaml
env:
- name: GOMAXPROCS
  valueFrom:
    resourceFieldRef:
      resource: limits.cpu
resources:
  requests:
    memory: 128Mi
    cpu: 500m
  limits:
    memory: 256Mi
    cpu: 1000m
```
https://www.youtube.com/watch?v=h2pCxj_Fkdc&t=984s

<img width="1246" alt="Screenshot 2024-10-03 at 12 41 02 AM" src="https://github.com/user-attachments/assets/2062931e-8a49-4ee5-9431-e0cec37a6a0b">
